apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: ampirchert/sys-demo-repo:service2
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: default
spec:
  type: NodePort
  selector:
    app: service2
  ports:
  - port: 80
    nodePort: 31002